leads = [
{'domain': 'arcare.com.au', 'fullname': 'Mal Humphries', 'position': None, 'email': 'mal.humphries@arcare.com.au', 'score': 99, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'arcare.com.au', 'fullname': 'Neil Roper', 'position': None, 'email': 'neil.roper@arcare.com.au', 'score': 98, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'arcare.com.au', 'fullname': 'Hans Wicht', 'position': 'General Manager', 'email': 'hans.wicht@arcare.com.au', 'score': 95, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/hans-wicht-06030046', 'phone_number': None}
{'domain': 'arcare.com.au', 'fullname': 'Katrina Rigby', 'position': None, 'email': 'katrina.rigby@arcare.com.au', 'score': 99, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'mckenziecare.com.au', 'fullname': 'Kevin Mckenzie', 'position': "Head Chef", 'email': 'kevin@mckenziecare.com.au', 'score': 98, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'mckenziecare.com.au', 'fullname': 'Dianna Sliogeris', 'position': "Deputy Director of Nursing", 'email': 'dianna@mckenziecare.com.au', 'score': 89, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'mckenziecare.com.au', 'fullname': 'Craig Healy', 'position': "Head Chef", 'email': 'craig@mckenziecare.com.au', 'score': 90, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'mckenziecare.com.au', 'fullname': 'Jorgie Hopewell', 'position': "Supervisor", 'email': 'jorgie@mckenziecare.com.au', 'score': 70, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'mckenziecare.com.au', 'fullname': 'Karen Secombe', 'position': "Regional Sales Manager", 'email': 'karen@mckenziecare.com.au', 'score': 87, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'mckenziecare.com.au', 'fullname': 'Sally McKenzie', 'position': "Director", 'email': 'sally@mckenziecare.com.au', 'score': 93, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'amanaliving.com.au', 'fullname': 'Stephanie Buckland', 'position': 'Chief Executive Officer', 'email': 'sbuckland@amanaliving.com.au', 'score': 99, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'amanaliving.com.au', 'fullname': 'Lee Watson', 'position': 'Chief Financial Officer', 'email': 'lwatson@amanaliving.com.au', 'score': 97, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/leewatson1', 'phone_number': None}
{'domain': 'amanaliving.com.au', 'fullname': 'None None', 'position': 'Chief Operating Officer', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'amanaliving.com.au', 'fullname': 'None None', 'position': 'Senior Accounts Receivable Officer & Credit Controller', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'amanaliving.com.au', 'fullname': 'Rachael Turner', 'position': 'Head of Human Resources', 'email': 'rturner@amanaliving.com.au', 'score': 98, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'amanaliving.com.au', 'fullname': 'Wendy Chibi', 'position': 'Clinical Nurse Manager', 'email': 'wchibi@amanaliving.com.au', 'score': 98, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'amanaliving.com.au', 'fullname': 'None None', 'position': 'General Manager, Residential Operations', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'arrcs.org.au', 'fullname': 'Wendy Hubbard', 'position': 'Chief Executive Officer', 'email': 'wendy.hubbard@arrcs.org.au', 'score': 96, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/wendy-hubbard-a7464510a', 'phone_number': None}
{'domain': 'arrcs.org.au', 'fullname': 'Jessica Dobbs', 'position': 'Executive Manager, Corporate Services', 'email': 'jessica.dobbs@arrcs.org.au', 'score': 97, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'arrcs.org.au', 'fullname': 'Rosie Breen', 'position': 'Aged Care Service Manager', 'email': 'rosie.breen@arrcs.org.au', 'score': 95, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'arrcs.org.au', 'fullname': 'Lynette Parkhill', 'position': 'Integrated Service Manager', 'email': 'lynette.parkhill@arrcs.org.au', 'score': 97, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'arrcs.org.au', 'fullname': 'Thibault Menier', 'position': 'Relief Service and Nurse Manager', 'email': 'thibault.menier@arrcs.org.au', 'score': 98, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'arrcs.org.au', 'fullname': 'None None', 'position': 'Director', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'arrcs.org.au', 'fullname': 'Michelle Watkins', 'position': 'Manager, People & Culture', 'email': 'michelle.watkins@arrcs.org.au', 'score': 96, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'arrcs.org.au', 'fullname': 'Jenny Messell', 'position': 'Service Manager', 'email': 'jenny.messell@arrcs.org.au', 'score': 98, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'baptcare.org.au', 'fullname': 'None None', 'position': 'Chief Executive Officer', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'baptcare.org.au', 'fullname': 'Georgie Crockett', 'position': 'Quality Head', 'email': 'gcrockett@baptcare.org.au', 'score': 99, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'baptcare.org.au', 'fullname': 'None None', 'position': 'Director of Nursing', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'baptcare.org.au', 'fullname': 'None None', 'position': 'Retirement Living Head', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'baptcare.org.au', 'fullname': 'None None', 'position': 'Chief Acting People Officer', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'baptcare.org.au', 'fullname': 'Shannon Jeffs', 'position': 'Cyber & Infrastructure Head', 'email': 'sjeffs@baptcare.org.au', 'score': 97, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/shannon-jeffs-543a584', 'phone_number': None}
{'domain': 'baptcare.org.au', 'fullname': 'Abhijit Kadam', 'position': 'Head of Solution Delivery', 'email': 'akadam@baptcare.org.au', 'score': 96, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/pingabhi', 'phone_number': None}
{'domain': 'baptcare.org.au', 'fullname': 'Shaun Jacobs', 'position': 'Head of Practice and Clinical Care', 'email': 'sjacobs@baptcare.org.au', 'score': 97, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/shaun-jacobs-550272213', 'phone_number': None}
{'domain': 'baptcare.org.au', 'fullname': 'Harvey Wang', 'position': 'Head Chef', 'email': 'h.wang@baptcare.org.au', 'score': 96, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'baptcare.org.au', 'fullname': 'Rebekah Stockdale', 'position': 'Head of Service Delivery', 'email': 'rstockdale@baptcare.org.au', 'score': 98, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'baptcare.org.au', 'fullname': 'Stephen Hogan', 'position': 'Head of Procurement', 'email': 's.hogan@baptcare.org.au', 'score': 99, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'baptcare.org.au', 'fullname': 'John Timmer', 'position': 'Manager, Housing Development', 'email': 'jtimmer@baptcare.org.au', 'score': 95, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'baptcare.org.au', 'fullname': 'None None', 'position': 'Chief Financial Officer', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'baptcare.org.au', 'fullname': 'None None', 'position': 'Chief Information and Digital Officer', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'baptcare.org.au', 'fullname': 'Gary Racine', 'position': 'General Manager Aged Care', 'email': 'gracine@baptcare.org.au', 'score': 98, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'hammond.com.au', 'fullname': 'Rory Crout', 'position': 'Chief Financial Officer', 'email': 'rcrout@hammond.com.au', 'score': 93, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'hammond.com.au', 'fullname': 'Victoria Hayman', 'position': 'Chief Marketing Officer & General Manager, Communications', 'email': 'vhayman@hammond.com.au', 'score': 93, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'hammond.com.au', 'fullname': 'Praneel Anand', 'position': 'Acting Chief Information Officer', 'email': 'praneel.anand@hammond.com.au', 'score': 72, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'hammond.com.au', 'fullname': 'Kasun Haputhanthri', 'position': 'Acting Chief Information Officer (Co)', 'email': 'khaputhanthri@hammond.com.au', 'score': 73, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'hammond.com.au', 'fullname': 'Angela Sacks', 'position': 'Chief Risk Officer & Chief Revenue Officer', 'email': 'asacks@hammond.com.au', 'score': 93, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'hammond.com.au', 'fullname': 'Andrew Cole', 'position': 'Chief Medical Officer & Senior Rehabilitation Physician', 'email': 'acole@hammond.com.au', 'score': 95, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'hammond.com.au', 'fullname': 'Jo Reed', 'position': 'Chief People Officer', 'email': 'jreed@hammond.com.au', 'score': 86, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'hammond.com.au', 'fullname': 'Theresa Krebs', 'position': 'Deputy Chief Financial Officer', 'email': 'tkrebs@hammond.com.au', 'score': 93, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'hammond.com.au', 'fullname': 'Sandeep Tut', 'position': 'Financial Controller', 'email': 'stut@hammond.com.au', 'score': 78, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'hammond.com.au', 'fullname': 'John Sutherland', 'position': 'Chief Information Officer', 'email': 'sjohn@hammond.com.au', 'score': 94, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'anglicaresq.org.au', 'fullname': 'Sue Cooke', 'position': 'Chief Executive Officer', 'email': 'scooke@anglicaresq.org.au', 'score': 96, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/sue-cooke-25899846', 'phone_number': None}
{'domain': 'anglicaresq.org.au', 'fullname': 'Anna Zilli', 'position': 'Chief Operating Officer, Corporate Services', 'email': 'azilli@anglicaresq.org.au', 'score': 99, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/anna-zilli-15150b89', 'phone_number': None}
{'domain': 'anglicaresq.org.au', 'fullname': 'Kane Singh', 'position': 'Chief Operating Officer, Aged & Community Services', 'email': 'ksingh@anglicaresq.org.au', 'score': 96, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/kane-singh-8b822298', 'phone_number': None}
{'domain': 'anglicaresq.org.au', 'fullname': 'Stephen Harrison', 'position': 'Director, Mission, Research & Advocacy', 'email': 'sharrison2@anglicaresq.org.au', 'score': 95, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'anglicaresq.org.au', 'fullname': 'Tehgan Samios', 'position': 'Chief Digital Officer', 'email': 'tsamios@anglicaresq.org.au', 'score': 97, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/tehgan-samios-a67b62114', 'phone_number': None}
{'domain': 'anglicaresq.org.au', 'fullname': 'Lorraine Damme', 'position': 'Director of Nursing', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'anglicaresq.org.au', 'fullname': 'Corryn Baker', 'position': 'Head of Financial Planning & Analysis', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'anglicaresq.org.au', 'fullname': 'Jennifer Loakes', 'position': 'Head of Organisational Development & Talent', 'email': 'jloakes@anglicaresq.org.au', 'score': 95, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/jennifer-loakes-13b56a48', 'phone_number': None}
{'domain': 'anglicaresq.org.au', 'fullname': 'Helen Sullivan', 'position': 'Acting Head of Organisational Development & Talent', 'email': 'hsullivan@anglicaresq.org.au', 'score': 98, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/hsullivan1', 'phone_number': None}
{'domain': 'anglicaresq.org.au', 'fullname': 'Tammy Lloyd', 'position': 'Chief Operating Officer, Children, Youth and Families', 'email': 'tlloyd@anglicaresq.org.au', 'score': 97, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'anglicare.org.au', 'fullname': 'Simon Miller', 'position': 'Chief Executive Officer', 'email': 'simon.miller@anglicare.org.au', 'score': 99, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'anglicare.org.au', 'fullname': 'Greg Muddle', 'position': 'Chief Financial Officer', 'email': 'greg.muddle@anglicare.org.au', 'score': 97, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/greg-muddle-74a43b27', 'phone_number': None}
{'domain': 'anglicare.org.au', 'fullname': 'Sarah Ramsey', 'position': 'Chief Operating Officer, Residential Care', 'email': 'sarah.ramsey@anglicare.org.au', 'score': 98, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'anglicare.org.au', 'fullname': 'Mick Simon', 'position': 'Chief Information Officer', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'anglicare.org.au', 'fullname': 'Nathan Mares', 'position': 'IT Director', 'email': 'nmares@anglicare.org.au', 'score': 98, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'anglicare.org.au', 'fullname': 'Lauren White', 'position': 'Chief of Staff', 'email': 'lauren.white@anglicare.org.au', 'score': 96, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/laurenjwhite', 'phone_number': None}
{'domain': 'anglicare.org.au', 'fullname': 'Rob Stokes', 'position': 'Group Executive, Housing', 'email': 'rob.stokes@anglicare.org.au', 'score': 98, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/robgstokes', 'phone_number': None}
{'domain': 'anglicare.org.au', 'fullname': 'Kylie White', 'position': 'Head of Human Resources', 'email': 'kylie.white@anglicare.org.au', 'score': 99, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'anglicare.org.au', 'fullname': 'Carien Labuschagne', 'position': 'Financial Controller', 'email': 'carien.labuschagne@anglicare.org.au', 'score': 95, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'anglicare.org.au', 'fullname': 'Victoria Lee', 'position': 'Chief Strategy and Transformation Officer', 'email': 'victoria.lee@anglicare.org.au', 'score': 99, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/victorialee288', 'phone_number': None}
{'domain': 'anglicare.org.au', 'fullname': 'Yvette Casement', 'position': 'Chief People and Customer Officer', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'anglicare.org.au', 'fullname': 'Robert Wallace', 'position': 'Director, Strategic Development', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'wmq.org.au', 'fullname': 'Jude Emmer', 'position': 'Chief Executive Officer', 'email': 'jemmer@wmq.org.au', 'score': 97, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'wmq.org.au', 'fullname': 'Jonathan King', 'position': 'Chief Financial Officer', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'wmq.org.au', 'fullname': 'Selina Beauchamp', 'position': 'Director of Organisational Transformation & CIO', 'email': 's.beauchamp@wmq.org.au', 'score': 95, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/selina-beauchamp-7b461aa0', 'phone_number': None}
{'domain': 'wmq.org.au', 'fullname': 'Darshan Parmar', 'position': 'Head of Marketing', 'email': 'dparmar@wmq.org.au', 'score': 96, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/darshanparmar', 'phone_number': None}
{'domain': 'wmq.org.au', 'fullname': 'Danielle Sullivan', 'position': 'Chief of Staff & Company Secretary', 'email': 'd.sullivan@wmq.org.au', 'score': 97, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'wmq.org.au', 'fullname': 'Tracey Green', 'position': 'Director of People & Culture', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'southerncrosscare.com.au', 'fullname': 'David Moran', 'position': 'Chief Executive Officer (SA, NT & VIC)', 'email': 'dmoran@southerncrosscare.com.au', 'score': 98, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'southerncrosscare.com.au', 'fullname': 'Monique Reynolds', 'position': 'Chief Executive Officer (NSW & ACT)', 'email': 'monique.reynolds@southerncrosscare.com.au', 'score': 98, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'southerncrosscare.com.au', 'fullname': 'Michael Bendyk', 'position': 'Chief Executive Officer (WA)', 'email': 'michael.bendyk@southerncrosscare.com.au', 'score': 99, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/michael-bendyk-4696b096', 'phone_number': None}
{'domain': 'southerncrosscare.com.au', 'fullname': 'Tanya Minton', 'position': 'Head of Communications & Marketing', 'email': 'tanya.minton@southerncrosscare.com.au', 'score': 95, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'southerncrosscare.com.au', 'fullname': 'ChongK Liow', 'position': 'Chief Financial Officer', 'email': 'chongk.liow@southerncrosscare.com.au', 'score': 84, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'southerncrosscare.com.au', 'fullname': 'Katrina Masalkar', 'position': 'Chief Information Officer', 'email': 'katrina.masalkar@southerncrosscare.com.au', 'score': 85, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'southerncrosscare.com.au', 'fullname': 'Mark Botsford', 'position': 'Chief Technology Officer / Chief of Business', 'email': 'mark.botsford@southerncrosscare.com.au', 'score': 96, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'southerncrosscare.com.au', 'fullname': 'Kate Beven', 'position': 'Chief People Officer', 'email': 'kate.beven@southerncrosscare.com.au', 'score': 98, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'southerncrosscare.com.au', 'fullname': 'Stephanie Petkovski', 'position': 'Chief Digital & Transformation Officer', 'email': 'stephanie.petkovski@southerncrosscare.com.au', 'score': 86, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'anglicarevic.org.au', 'fullname': 'Paul McDonald', 'position': 'Chief Executive Officer', 'email': 'paul.mcdonald@anglicarevic.org.au', 'score': 93, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'anglicarevic.org.au', 'fullname': 'Sue Sealey', 'position': 'Deputy Chief Executive Officer', 'email': 'sue.sealey@anglicarevic.org.au', 'score': 97, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/sue-sealey-b1a68752', 'phone_number': None}
{'domain': 'anglicarevic.org.au', 'fullname': 'Ian Bennett', 'position': 'Chief Financial Officer', 'email': 'ian.bennett@anglicarevic.org.au', 'score': 86, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'anglicarevic.org.au', 'fullname': 'Kirsty Simpson', 'position': 'Director, Strategic Communications & Marketing', 'email': 'kirsty.simpson@anglicarevic.org.au', 'score': 97, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/kirsty-simpson-51b98b36', 'phone_number': None}
{'domain': 'anglicarevic.org.au', 'fullname': 'Vincent Bucci', 'position': 'Director, Finance & Business Services', 'email': 'vincent.bucci@anglicarevic.org.au', 'score': 98, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/vincent-bucci-0ab9b032', 'phone_number': None}
{'domain': 'anglicarevic.org.au', 'fullname': 'Rosanna Wilson', 'position': 'Marketing and Communications Manager', 'email': 'rosanna.wilson@anglicarevic.org.au', 'score': 93, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'anglicarevic.org.au', 'fullname': 'Kiera Outlaw', 'position': 'Digital Marketing Manager', 'email': 'kiera.outlaw@anglicarevic.org.au', 'score': 90, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'missionaustralia.com.au', 'fullname': 'Sharon Callister', 'position': 'Chief Executive Officer', 'email': 'callisters@missionaustralia.com.au', 'score': 93, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'missionaustralia.com.au', 'fullname': 'Ben Carblis', 'position': 'Deputy Chief Executive Officer', 'email': 'carblisb@missionaustralia.com.au', 'score': 73, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/ben-carblis-6a959547', 'phone_number': None}
{'domain': 'missionaustralia.com.au', 'fullname': 'Peter Smith', 'position': 'Chief Information Officer', 'email': 'peter-s@missionaustralia.com.au', 'score': 83, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'missionaustralia.com.au', 'fullname': 'Elissa Webster', 'position': 'Head of Marketing & Fundraising', 'email': 'webstere@missionaustralia.com.au', 'score': 77, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'missionaustralia.com.au', 'fullname': 'Kelvin Payne', 'position': 'Group Financial Controller', 'email': 'paynek@missionaustralia.com.au', 'score': 90, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'missionaustralia.com.au', 'fullname': 'Dianne Jackson', 'position': 'Chief Operations Officer', 'email': 'jacksond@missionaustralia.com.au', 'score': 83, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'missionaustralia.com.au', 'fullname': 'Chris Bratchford', 'position': 'Executive, Mission Australia Housing', 'email': 'bratchfordc@missionaustralia.com.au', 'score': 74, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'missionaustralia.com.au', 'fullname': 'Saam Poushin', 'position': 'Deputy Chief Information Officer', 'email': 'poushins@missionaustralia.com.au', 'score': 64, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'missionaustralia.com.au', 'fullname': 'Gillian Brinsden', 'position': 'Chief People Officer', 'email': 'brinsdeng@missionaustralia.com.au', 'score': 65, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'bluecare.org.au', 'fullname': 'Ben Edwards', 'position': 'Chief Executive Officer (UnitingCare Queensland)', 'email': 'b.edwards@bluecare.org.au', 'score': 90, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'bluecare.org.au', 'fullname': 'Cathy Thomas', 'position': 'Group Executive, Aged Care & Community Services', 'email': 'c.thomas@bluecare.org.au', 'score': 98, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'bluecare.org.au', 'fullname': 'Natalie Schmidt', 'position': 'Chief Operating Officer', 'email': 'n.schmidt@bluecare.org.au', 'score': 91, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'bluecare.org.au', 'fullname': 'Leith MacMillan', 'position': 'General Manager, Marketing & Communications', 'email': 'l.macmillan@bluecare.org.au', 'score': 85, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'bluecare.org.au', 'fullname': 'Peter Armstrong', 'position': 'Director of Mission', 'email': 'p.armstrong@bluecare.org.au', 'score': 94, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'estiahealth.com.au', 'fullname': 'Sean Bilton', 'position': 'Chief Executive Officer & Managing Director', 'email': 'sean.bilton@estiahealth.com.au', 'score': 99, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/sean-bilton-b19a794', 'phone_number': None}
{'domain': 'estiahealth.com.au', 'fullname': 'Damian Hiser', 'position': 'Chief Operating Officer', 'email': 'damian.hiser@estiahealth.com.au', 'score': 99, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/damian-hiser-58ab618', 'phone_number': None}
{'domain': 'estiahealth.com.au', 'fullname': 'Ciara Rocks', 'position': 'Chief Customer and Commercial Officer', 'email': 'ciara.rocks@estiahealth.com.au', 'score': 95, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/ciara-rocks-100b0177', 'phone_number': None}
{'domain': 'estiahealth.com.au', 'fullname': 'Fiona Caldwell', 'position': 'Chief Information Officer', 'email': 'fionacaldwell@estiahealth.com.au', 'score': 93, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/fionacaldwell', 'phone_number': None}
{'domain': 'estiahealth.com.au', 'fullname': 'Jodie Gacitua', 'position': 'Head of Marketing Communications', 'email': 'jodie.gacitua@estiahealth.com.au', 'score': 95, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/jodiemgacitua', 'phone_number': None}
{'domain': 'estiahealth.com.au', 'fullname': 'Sam Winter', 'position': 'Chief Business Development Officer', 'email': 'sam.winter@estiahealth.com.au', 'score': 99, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/sam-winter-65496242', 'phone_number': None}
{'domain': 'estiahealth.com.au', 'fullname': 'Dianna Gu', 'position': 'Chief Legal and Risk Officer', 'email': 'dianna.gu@estiahealth.com.au', 'score': 71, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'silverchain.org.au', 'fullname': 'Dale Fisher', 'position': 'Chief Executive Officer', 'email': 'dale.fisher@silverchain.org.au', 'score': 97, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'silverchain.org.au', 'fullname': 'Hiren Mehta', 'position': 'Chief Financial Officer', 'email': 'hiren.mehta@silverchain.org.au', 'score': 99, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/hiren-mehta-mba-ca-anz-fcca-uk-9b4b9431', 'phone_number': None}
{'domain': 'silverchain.org.au', 'fullname': 'James Wagg', 'position': 'Chief Commercial Officer', 'email': 'james.wagg@silverchain.org.au', 'score': 96, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'silverchain.org.au', 'fullname': 'Suzanne Hall', 'position': 'Chief Information Officer', 'email': 'suzanne.hall@silverchain.org.au', 'score': 97, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'silverchain.org.au', 'fullname': 'Aaron Burt', 'position': 'Chief Technology Officer', 'email': 'aaron.burt@silverchain.org.au', 'score': 98, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/aaron-burt-6b4b8659', 'phone_number': None}
{'domain': 'silverchain.org.au', 'fullname': 'Bronwyn Perry', 'position': 'Executive Director, Strategic Communications', 'email': 'bronwyn.perry@silverchain.org.au', 'score': 98, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/bronwyn-perry-713144a9', 'phone_number': None}
{'domain': 'silverchain.org.au', 'fullname': 'Bethany Willsmore', 'position': 'Director, Brand & Marketing', 'email': 'bethany.willsmore@silverchain.org.au', 'score': 97, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/bethany-willsmore-74097143', 'phone_number': None}
{'domain': 'silverchain.org.au', 'fullname': 'Lisa Dunlop', 'position': 'Executive Director, People & Care Governance', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'juniper.org.au', 'fullname': 'Russell Bricknell', 'position': 'Chief Executive Officer', 'email': 'russell.bricknell@juniper.org.au', 'score': 87, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/rbricknell', 'phone_number': None}
{'domain': 'juniper.org.au', 'fullname': 'Jodie Wallace', 'position': 'Chief Operating Officer - Care', 'email': 'jodiewallace@juniper.org.au', 'score': 92, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'juniper.org.au', 'fullname': 'Jacob Hollenberg', 'position': 'Chief Operating Officer - Accommodation', 'email': 'jacob.hollenberg@juniper.org.au', 'score': 80, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'juniper.org.au', 'fullname': 'Rohan McCarthy-Gorton', 'position': 'Chief Financial Officer', 'email': 'rohanmccarthy-gorton@juniper.org.au', 'score': 66, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'juniper.org.au', 'fullname': 'Emma Coles', 'position': 'Chief People Officer', 'email': 'emmacoles@juniper.org.au', 'score': 91, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'juniper.org.au', 'fullname': 'Danielle Nanini', 'position': 'Chief Customer and Innovation Officer', 'email': 'daniellenanini@juniper.org.au', 'score': 69, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'juniper.org.au', 'fullname': 'Melanie Smorenburg-Trim', 'position': 'Director, Customer and Brand', 'email': 'melaniesmorenburg-trim@juniper.org.au', 'score': 67, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'wesleymission.org.au', 'fullname': 'Stuart Cameron', 'position': 'CEO and Superintendent', 'email': 'stuart.cameron@wesleymission.org.au', 'score': 91, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'wesleymission.org.au', 'fullname': 'Karen James', 'position': 'Executive Director - Strategy, People and Partnerships', 'email': 'karen.james@wesleymission.org.au', 'score': 93, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'wesleymission.org.au', 'fullname': 'Mark Broadhead', 'position': 'Executive Director - Finance, Property & Information Services', 'email': 'mark.broadhead@wesleymission.org.au', 'score': 91, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'wesleymission.org.au', 'fullname': 'David Cannings', 'position': 'Chief Financial Officer', 'email': 'david.cannings@wesleymission.org.au', 'score': 74, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'wesleymission.org.au', 'fullname': 'Judi Lewis', 'position': 'Executive General Manager - Marketing & Fundraising', 'email': 'judi.lewis@wesleymission.org.au', 'score': 97, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/judi-lewis-73555a52', 'phone_number': None}
{'domain': 'wesleymission.org.au', 'fullname': 'Dawn James', 'position': 'Head of Marketing', 'email': 'dawn.james@wesleymission.org.au', 'score': 98, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/dawnjames-', 'phone_number': None}
{'domain': 'wesleymission.org.au', 'fullname': 'Bay Warburton', 'position': 'Executive Director - Community Services', 'email': 'bay.warburton@wesleymission.org.au', 'score': 89, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'wesleymission.org.au', 'fullname': 'Aldo Travia', 'position': 'Chief Investments and Assets Officer', 'email': 'aldo.travia@wesleymission.org.au', 'score': 95, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/aldotravia', 'phone_number': None}
{'domain': 'catholichealthcare.com.au', 'fullname': 'Joshua McFarlane', 'position': 'Chief Executive Officer', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'catholichealthcare.com.au', 'fullname': 'Michael Czekner', 'position': 'Chief Financial Officer', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'catholichealthcare.com.au', 'fullname': 'Brett Reedman', 'position': 'Chief Information Officer', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'chcs.com.au', 'fullname': 'Catherine McMahon', 'position': 'Chief People Officer', 'email': 'catherine.mcmahon@chcs.com.au', 'score': 97, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'catholichealthcare.com.au', 'fullname': 'Andrew Watson', 'position': 'Director, Mission Integration', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'catholichealthcare.com.au', 'fullname': 'Ethel Mizenko', 'position': 'Director, Admissions & Marketing', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'catholichealthcare.com.au', 'fullname': 'Kirsten Mead', 'position': 'Executive Director, Residential Care', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'catholichealthcare.com.au', 'fullname': 'Philip Mulhall', 'position': 'Director, Enterprise Project Management Office', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'resthaven.asn.au', 'fullname': 'Darren Birbeck', 'position': 'Chief Executive Officer', 'email': 'darren.birbeck@resthaven.asn.au', 'score': 96, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'resthaven.asn.au', 'fullname': 'Rob Quinton', 'position': 'Chief Finance Officer', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'resthaven.asn.au', 'fullname': 'James Barona', 'position': 'Chief Technology Officer', 'email': 'james.barona@resthaven.asn.au', 'score': 99, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'resthaven.asn.au', 'fullname': 'Melanie Ottaway', 'position': 'Executive Manager, Community Services & Retirement Living', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'resthaven.asn.au', 'fullname': 'Sylvia Powell', 'position': 'Executive Manager, People and Culture', 'email': 'sylvia.powell@resthaven.asn.au', 'score': 99, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/sylvia-powell-2866bb58', 'phone_number': None}
{'domain': 'resthaven.asn.au', 'fullname': 'Merridy Baylis', 'position': 'Executive Manager, Clinical Governance and Operational Excellence', 'email': 'merridy.baylis@resthaven.asn.au', 'score': 98, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/merridy-baylis-94b3ba360', 'phone_number': None}
{'domain': 'resthaven.asn.au', 'fullname': 'Kelly Geister', 'position': 'Executive Manager, Residential Services', 'email': 'kelly.geister@resthaven.asn.au', 'score': 98, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/kelly-geister-16060095', 'phone_number': None}
{'domain': 'resthaven.asn.au', 'fullname': 'Di Kelly', 'position': 'Senior Marketing and Communications Advisor', 'email': 'dkelly@resthaven.asn.au', 'score': 98, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'baptistcare.org.au', 'fullname': 'Charles Moore', 'position': 'Chief Executive Officer', 'email': 'cmoore@baptistcare.org.au', 'score': 98, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/chmoore1', 'phone_number': None}
{'domain': 'baptistcare.org.au', 'fullname': 'Neville Zammit', 'position': 'Chief Financial Officer', 'email': 'nzammit@baptistcare.org.au', 'score': 95, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/nevillezammit', 'phone_number': None}
{'domain': 'baptistcare.org.au', 'fullname': 'Amanda Vivian', 'position': 'Executive General Manager, Office of the CEO (Strategy & Customer Experience)', 'email': 'amandavivian@baptistcare.org.au', 'score': 92, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/amanda-vivian-5125b82a', 'phone_number': None}
{'domain': 'baptistcare.org.au', 'fullname': 'Daniel Pettman', 'position': 'Chief Information and Digital Officer', 'email': 'daniel.pettman@baptistcare.org.au', 'score': 59, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'baptistcare.org.au', 'fullname': 'Silvia Alberti', 'position': 'Executive General Manager, Quality and Innovation', 'email': 'salberti@baptistcare.org.au', 'score': 85, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'baptistcare.org.au', 'fullname': 'Liz de Berardis', 'position': 'Executive General Manager, People and Culture', 'email': 'lde-berardis@baptistcare.org.au', 'score': 57, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'baptistcare.org.au', 'fullname': 'Kate Barber', 'position': 'Executive General Manager, Chief of Staff (Legal & Risk)', 'email': 'kbarber@baptistcare.org.au', 'score': 86, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'benetas.com.au', 'fullname': 'Sandra Hills OAM', 'position': 'Chief Executive Officer', 'email': 'sandra.hills-oam@benetas.com.au', 'score': 75, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'benetas.com.au', 'fullname': 'Campbell Richards', 'position': 'Chief Financial Officer & Company Secretary', 'email': 'campbell.richards@benetas.com.au', 'score': 75, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'benetas.com.au', 'fullname': 'John Staines', 'position': 'Chief Information Officer', 'email': 'john.staines@benetas.com.au', 'score': 95, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/johnstaines', 'phone_number': None}
{'domain': 'benetas.com.au', 'fullname': 'Elyssia Clark', 'position': 'General Manager, Customer, Insights and Marketing', 'email': 'elyssia.clark@benetas.com.au', 'score': 76, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'benetas.com.au', 'fullname': 'Alicia Goddard', 'position': 'General Manager, People, Culture and Diversity', 'email': 'alicia.goddard@benetas.com.au', 'score': 90, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'benetas.com.au', 'fullname': 'Bruce Webb', 'position': 'General Manager, Strategy, Infrastructure and Housing', 'email': 'bruce.webb@benetas.com.au', 'score': 99, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'benetas.com.au', 'fullname': 'Sarah McInerney', 'position': 'General Manager, Quality, Risk and Safeguarding', 'email': 'sarah.mcinerney@benetas.com.au', 'score': 94, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'benetas.com.au', 'fullname': 'Stella Tilkeridis', 'position': 'Communications Manager', 'email': 'stella.tilkeridis@benetas.com.au', 'score': 75, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'bethanie.com.au', 'fullname': 'Roule Jones', 'position': 'Chief Executive Officer', 'email': 'roule.jones@bethanie.com.au', 'score': 93, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/roulé-jones-170ab74b', 'phone_number': None}
{'domain': 'bethanie.com.au', 'fullname': 'Jacqui Hall', 'position': 'Interim Chief Financial Officer', 'email': 'jacqui.hall@bethanie.com.au', 'score': 88, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'bethanie.com.au', 'fullname': 'Marg Denton', 'position': 'Interim Chief Operating Officer', 'email': 'marg.denton@bethanie.com.au', 'score': 93, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'bethanie.com.au', 'fullname': 'Enzo Evangelista', 'position': 'Chief Property & Development Officer', 'email': 'enzo.evangelista@bethanie.com.au', 'score': 94, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'bethanie.com.au', 'fullname': 'Catherine Bentley', 'position': 'CEO, Bethanie Housing Limited', 'email': 'catherine.bentley@bethanie.com.au', 'score': 93, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'bethanie.com.au', 'fullname': 'Justin Scanlan', 'position': 'Chief Information Officer', 'email': 'justin.scanlan@bethanie.com.au', 'score': 93, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'bethanie.com.au', 'fullname': 'Sheree Ritchie', 'position': 'General Manager, Residential Operations', 'email': 'sritchie@bethanie.com.au', 'score': 84, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'bethanie.com.au', 'fullname': 'Helen Jones', 'position': 'General Manager, Community', 'email': 'helen.jones@bethanie.com.au', 'score': 98, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/helenjones1', 'phone_number': None}
{'domain': 'ech.asn.au', 'fullname': 'Alan Morrison', 'position': 'Chief Executive Officer', 'email': 'alan.morrison@ech.asn.au', 'score': 95, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'ech.asn.au', 'fullname': 'Merrin Nancarrow', 'position': 'Head of Home and Community', 'email': 'mnancarrow@ech.asn.au', 'score': 96, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/merrin-nancarrow-891abb155', 'phone_number': None}
{'domain': 'ech.asn.au', 'fullname': 'Sharon Paulson', 'position': 'Head of Digital Workplace Services (CIO)', 'email': 'spaulson@ech.asn.au', 'score': 96, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/sharon-paulson-7a219413', 'phone_number': None}
{'domain': 'ech.asn.au', 'fullname': 'Carolyn Dawkins', 'position': 'Head of Customer Experience', 'email': 'cdawkins@ech.asn.au', 'score': 97, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/carolyn-dawkins-b39664259', 'phone_number': None}
{'domain': 'ech.asn.au', 'fullname': 'Melissa McDougall', 'position': 'Chief Technology Officer', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'ech.asn.au', 'fullname': 'Richard Laidlaw', 'position': 'Head of People and Culture', 'email': 'richard.laidlaw@ech.asn.au', 'score': 96, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'ech.asn.au', 'fullname': 'Alan Johncock', 'position': 'Head of Property & Retirement Living', 'email': 'ajohncock@ech.asn.au', 'score': 97, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/alanjohncock', 'phone_number': None}
{'domain': 'ech.asn.au', 'fullname': 'Scott McMullen', 'position': 'General Manager, Innovation and Business Development', 'email': 'smcmullen@ech.asn.au', 'score': 96, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'eldercare.net.au', 'fullname': 'Jane Pickering', 'position': 'Chief Executive Officer', 'email': 'jane.pickering@eldercare.net.au', 'score': 97, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/jane-pickering-164b314a', 'phone_number': None}
{'domain': 'eldercare.net.au', 'fullname': 'Scott Morgan', 'position': 'Corporate Services Executive (CFO/CIO)', 'email': 'scott.morgan@eldercare.net.au', 'score': 97, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/scott-morgan-28370822', 'phone_number': None}
{'domain': 'eldercare.net.au', 'fullname': 'Anne-Marie Gillard', 'position': 'Operational Services Executive (COO)', 'email': 'anne-marie.gillard@eldercare.net.au', 'score': 97, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/anne-marie-gillard-81694644', 'phone_number': None}
{'domain': 'eldercare.net.au', 'fullname': 'Troy Seidel', 'position': 'General Manager, Technology', 'email': 'troy.seidel@eldercare.net.au', 'score': 95, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/troy-seidel-30ba4943', 'phone_number': None}
{'domain': 'eldercare.net.au', 'fullname': 'Adam Yeomans', 'position': 'General Manager, Property', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'eldercare.net.au', 'fullname': 'Melia Stone', 'position': 'General Manager, People', 'email': 'melia.stone@eldercare.net.au', 'score': 95, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/melia-stone-b18b3960', 'phone_number': None}
{'domain': 'eldercare.net.au', 'fullname': 'Michael Searle', 'position': 'General Manager, Governance, Risk & Compliance', 'email': 'michael.searle@eldercare.net.au', 'score': 99, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/michael-searle-9349963a', 'phone_number': None}
{'domain': 'eldercare.net.au', 'fullname': 'Nicole Cox', 'position': 'General Manager, Finance', 'email': 'nicole.cox@eldercare.net.au', 'score': 96, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/nicole-cox-93672385', 'phone_number': None}
{'domain': 'montefiore.org.au', 'fullname': 'Robert Orie', 'position': 'Chief Executive Officer', 'email': 'robertorie@montefiore.org.au', 'score': 95, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/robert-orie-60534b82', 'phone_number': None}
{'domain': 'montefiore.org.au', 'fullname': 'Tracey Cumbers', 'position': 'Chief Operating Officer', 'email': 'traceycumbers@montefiore.org.au', 'score': 76, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'montefiore.org.au', 'fullname': 'Anton Verkroost-Clark', 'position': 'Chief Financial Officer', 'email': 'averkroost-clark@montefiore.org.au', 'score': 86, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/anton-verkroost-clark-5660671b', 'phone_number': None}
{'domain': 'montefiore.org.au', 'fullname': 'Rudy De Vos', 'position': 'Chief Information Officer', 'email': 'rudyde-vos@montefiore.org.au', 'score': 84, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'montefiore.org.au', 'fullname': 'Gabbie Budai', 'position': 'General Manager, Client Experience & Marketing', 'email': 'gabbiebudai@montefiore.org.au', 'score': 76, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'montefiore.org.au', 'fullname': 'Anna Santikos', 'position': 'Director, People, Culture & Learning', 'email': 'annasantikos@montefiore.org.au', 'score': 89, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/anna-santikos-468a9885', 'phone_number': None}
{'domain': 'montefiore.org.au', 'fullname': 'Sabrina Scandurra', 'position': 'Director, Quality & Clinical Governance', 'email': 'sabrinascandurra@montefiore.org.au', 'score': 93, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'montefiore.org.au', 'fullname': 'Colin Henderson', 'position': 'General Manager, Property & Risk', 'email': 'colinhenderson@montefiore.org.au', 'score': 93, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'feroscare.com.au', 'fullname': 'Karen Crouch', 'position': 'Chief Executive Officer', 'email': 'karencrouch@feroscare.com.au', 'score': 97, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/karen-crouch-b65a84189', 'phone_number': None}
{'domain': 'feroscare.com.au', 'fullname': 'Nigel Rennie', 'position': 'Chief Information Officer', 'email': 'nigelrennie@feroscare.com.au', 'score': 96, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/nigel-rennie-3a72b2b', 'phone_number': None}
{'domain': 'feroscare.com.au', 'fullname': 'Robyn Schneider', 'position': 'Chief Operating Officer, Residential & Facilities', 'email': 'robyn.schneider@feroscare.com.au', 'score': 95, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'feroscare.com.au', 'fullname': 'Melissa Simpson', 'position': 'Chief Customer Officer', 'email': 'melissasimpson@feroscare.com.au', 'score': 96, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/melissa-simpson-35b2a031', 'phone_number': None}
{'domain': 'feroscare.com.au', 'fullname': 'David Spurgeon', 'position': 'General Manager, Transformation', 'email': 'davidspurgeon@feroscare.com.au', 'score': 95, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/david-spurgeon-a814612', 'phone_number': None}
{'domain': 'feroscare.com.au', 'fullname': 'Rebecca Chivers', 'position': 'General Manager, Community Development', 'email': 'rebeccachivers@feroscare.com.au', 'score': 96, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'swancare.com.au', 'fullname': 'Phil Martin', 'position': 'Chief Executive Officer', 'email': 'phil.martin@swancare.com.au', 'score': 96, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/phil-martin-79536b87', 'phone_number': None}
{'domain': 'swancare.com.au', 'fullname': 'Sinead McCartan', 'position': 'Chief Financial Officer', 'email': 'sinead.mccartan@swancare.com.au', 'score': 99, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/sinead-mccartan-fcca-caanz-a52711104', 'phone_number': None}
{'domain': 'swancare.com.au', 'fullname': 'Nicki Washington', 'position': 'Chief Operations Officer', 'email': 'nicki.washington@swancare.com.au', 'score': 95, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'swancare.com.au', 'fullname': 'Jae Smith', 'position': 'Chief Governance & Strategy Officer', 'email': 'jae.smith@swancare.com.au', 'score': 99, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'swancare.com.au', 'fullname': 'Darren Sumner', 'position': 'Chief Corporate Services Officer', 'email': 'darren.sumner@swancare.com.au', 'score': 96, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'swancare.com.au', 'fullname': 'Anne Hansen', 'position': 'Chief People & Culture Officer', 'email': 'anne.hansen@swancare.com.au', 'score': 96, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'swancare.com.au', 'fullname': 'Nancy Kingston', 'position': 'Head of Marketing Communications', 'email': 'nancy.kingston@swancare.com.au', 'score': 96, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/nmkingston', 'phone_number': None}
{'domain': 'mercycare.com.au', 'fullname': 'Anthony Smith', 'position': 'Chief Executive Officer', 'email': 'asmith@mercycare.com.au', 'score': 99, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'mercycare.com.au', 'fullname': 'Amelia Yam-Matacz', 'position': 'Chief Financial Officer', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'mercycare.com.au', 'fullname': 'Martin Wandmaker', 'position': 'Executive Director, People, Culture & Brand', 'email': 'mwandmaker@mercycare.com.au', 'score': 95, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/wandmaker', 'phone_number': None}
{'domain': 'mercycare.com.au', 'fullname': 'Rosina Smith', 'position': 'Executive Director, Early Learning Services', 'email': 'rsmith@mercycare.com.au', 'score': 97, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/rosina-smith-61588921b', 'phone_number': None}
{'domain': 'mercycare.com.au', 'fullname': 'Jennie Burns', 'position': 'Executive Director, Family & Community Services', 'email': 'jburns@mercycare.com.au', 'score': 98, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/jennie-burns-1a4528267', 'phone_number': None}
{'domain': 'mercycare.com.au', 'fullname': 'Vicky Gonzalez Burrows', 'position': 'Executive Director, Mission & Ethos', 'email': None, 'score': None, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'mercycare.com.au', 'fullname': 'Lauren Brazier', 'position': 'Executive Director, Aged Care', 'email': 'lbrazier@mercycare.com.au', 'score': 98, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'brightwatergroup.com', 'fullname': 'Catherine Stoddart', 'position': 'Chief Executive Officer', 'email': 'catherines@brightwatergroup.com', 'score': 98, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'brightwatergroup.com', 'fullname': 'David Holden', 'position': 'Chief Financial Officer', 'email': 'david.holden@brightwatergroup.com', 'score': 96, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'brightwatergroup.com', 'fullname': 'Kelly Worlock', 'position': 'Chief Operations Officer', 'email': 'kelly.worlock@brightwatergroup.com', 'score': 99, 'twitter': None, 'linkedin_url': None, 'phone_number': None}
{'domain': 'brightwatergroup.com', 'fullname': 'David Nicolaou', 'position': 'Chief Information Officer', 'email': 'david.nicolaou@brightwatergroup.com', 'score': 97, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/david-nicolaou-5676bb12', 'phone_number': None}
{'domain': 'brightwatergroup.com', 'fullname': 'Darren Woolcott', 'position': 'Chief Commercial Officer', 'email': 'darren.woolcott@brightwatergroup.com', 'score': 99, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/darren-woolcott1702', 'phone_number': None}
{'domain': 'brightwatergroup.com', 'fullname': 'Tracy Watts', 'position': 'General Manager, People & Culture', 'email': 'tracy.watts@brightwatergroup.com', 'score': 97, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/tracy-watts-2204b024b', 'phone_number': None}
{'domain': 'brightwatergroup.com', 'fullname': 'Andre Rauch', 'position': 'Manager, Marketing & Stakeholder Engagement', 'email': 'andre.rauch@brightwatergroup.com', 'score': 99, 'twitter': None, 'linkedin_url': 'https://www.linkedin.com/in/andre-rauch-38298125', 'phone_number': None}
]

# https://www.zoominfo.com/c/kincare-health-services-pty-ltd/104105290
# https://www.zoominfo.com/c/ozcare/60556564
# https://www.zoominfo.com/c/villa-maria-catholic-homes-ltd/112345206
# https://www.zoominfo.com/c/challenge-community-services/357530884
# https://www.zoominfo.com/c/cara-inc/347690387
# https://www.zoominfo.com/c/nextt/203669962
# https://www.zoominfo.com/c/retireaustralia-pty-ltd/354287940
# https://www.zoominfo.com/c/st-ives-group-pty-ltd/398301440
# https://www.zoominfo.com/c/craigcare/37408620?__cf_chl_rt_tk=SxqIzJQwXEZxAHFUyEiwHDUHA8pr9VSsK5pRq.7THBQ-1770544591-1.0.1.1-SvGTM0M886afG_pq2D.R3FxWXGroTzKVuSdSsN.IvD8
# https://www.zoominfo.com/c/lyndoch-living-ltd/347288339
# https://gemini.google.com/app/a62f394942802810
# https://colab.research.google.com/drive/1ZpJuPjhtmZHyArqoKHLYzJguuYix_emg#scrollTo=eHA4Rah9Gz94
